### ISSUE TITLE
Phone login not working

### ISSUE THREAD

**Issue by XanderG2** [house-778/house-778.github.io#3]
On my iPhone the login page isn't directing to the mobile login page which I assume it is meant to. I have no clue how to fix this as your code is obstructed.

Fix if you want idc because safari doesn't support we go anyway, I just wanted to see the updated terms.

**Comment by DFoster-2** [comment]
yes 
this is the code and it is in the login page
  if (window.innerWidth <= 768) {
    window.location.href = "mobillog.html";
  }

**Comment by DFoster-2** [comment]
if (/Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent)) {
    window.location.href = "mobillog.html";
  }
fixt it

**Comment by XanderG2** [comment]
Can confirm, it works!
